# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitComposer < Formula
  desc "Mark and recompose git commits in a TUI, with Claude-driven multi-commit redesign."
  homepage "https://github.com/mrcat71/commit-composer"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_darwin_amd64.tar.gz"
      sha256 "bdf93f72a6c2b09560c6bfa855a266bc8af6c06dbb4a5871c35f9e2cfab7d9b9"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_darwin_arm64.tar.gz"
      sha256 "48c16d8d808a4a7141427ba7510108d6b4ac31931ad484364a5536d362eb7e75"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_linux_amd64.tar.gz"
      sha256 "3f9ec9c5fbbdedbb6098ea16c188028a6d4c52caa118ef70e09ca8abb32f990c"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_linux_arm64.tar.gz"
      sha256 "ae33c7dc63bfe0a252c79628f8f9bd5417be5cb07c3d6d41d1aeda2babf8051e"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  test do
    system "#{bin}/commit-composer", "--version"
  end
end
