# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitComposer < Formula
  desc "Mark and recompose git commits in a TUI, with Claude-driven multi-commit redesign."
  homepage "https://github.com/mrcat71/commit-composer"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_darwin_amd64.tar.gz"
      sha256 "74dbc7f16ff1e7191b0f72bd5832a0791c4c564b2c16b30cface4991b6c98a1c"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_darwin_arm64.tar.gz"
      sha256 "da8fb9464f00eeb81737f5a9791fc115418009662227bd2901f4fe9d1360088e"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_linux_amd64.tar.gz"
      sha256 "1852c2113b56a88679b05c9e4e5a7dc9de237cb1ae3ecacb9d79ef53bf41b275"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.4/commit-composer_0.1.4_linux_arm64.tar.gz"
      sha256 "a5243f61714fe220eb6b4ee1be7bfe175ae9668477ae0dd43bde2a89498dfc47"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  test do
    system "#{bin}/commit-composer", "--version"
  end
end
