# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CommitComposer < Formula
  desc "Mark and recompose git commits in a TUI, with Claude-driven multi-commit redesign."
  homepage "https://github.com/mrcat71/commit-composer"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.5/commit-composer_0.1.5_darwin_amd64.tar.gz"
      sha256 "ec5363d4ec0c043a48bafa31c3e3cfd392502ccb552cacea46d13d147a1d69f3"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.5/commit-composer_0.1.5_darwin_arm64.tar.gz"
      sha256 "d0a82968bc04a34902afb09233ee6676a784d09ca5fe9d6a25bcdb5f1b817cd8"

      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.5/commit-composer_0.1.5_linux_amd64.tar.gz"
      sha256 "ee65c38ec3f10614a533f1498c7286ce61ed45b01ca60f0727f394500cc80f6b"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/commit-composer/releases/download/v0.1.5/commit-composer_0.1.5_linux_arm64.tar.gz"
      sha256 "cf0742874c1511249576fb7885a87ff3c3e06f16848d608af4d261eb21f51d5b"
      define_method(:install) do
        bin.install "commit-composer"
        # Ship the Claude Code plugin files so a single `brew install` gives
        # users the binary AND the slash command / skill / launcher. The path
        # `/opt/homebrew/share/commit-composer/.claude-plugin/` is stable across
        # versions (brew refreshes the symlink on every upgrade), so users
        # only need to run `/plugin marketplace add` once.
        (share/"commit-composer").install ".claude-plugin"
      end
    end
  end

  test do
    system "#{bin}/commit-composer", "--version"
  end
end
