# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opvar < Formula
  desc "Export 1Password secrets matched by tag as shell exports or JSON."
  homepage "https://github.com/mrcat71/opvar"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.1/opvar_0.1.1_darwin_amd64.tar.gz"
      sha256 "e3e0ed40aeaceb617af97bda19b7f1a4564978e7a671cfcaa576901d181c1915"

      define_method(:install) do
        bin.install "opvar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.1/opvar_0.1.1_darwin_arm64.tar.gz"
      sha256 "b2c4c8900b4a898f6bf058d9d18a2d20fa685cc9fba01261bdb545aba011c4b7"

      define_method(:install) do
        bin.install "opvar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.1/opvar_0.1.1_linux_amd64.tar.gz"
      sha256 "c5dec3f2c925d9f05dc73e518e9a65056916131638bb1d1a0d3a05b2f34ba04d"
      define_method(:install) do
        bin.install "opvar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.1/opvar_0.1.1_linux_arm64.tar.gz"
      sha256 "e8ee490a2cbce79b98c1c199994e2d93465392e25bc0350536c869a94f1858e9"
      define_method(:install) do
        bin.install "opvar"
      end
    end
  end

  test do
    system "#{bin}/opvar", "--version"
  end
end
