# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opvar < Formula
  desc "Export 1Password secrets matched by tag as shell exports or JSON."
  homepage "https://github.com/mrcat71/opvar"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.0/opvar_0.1.0_darwin_amd64.tar.gz"
      sha256 "70d228b5b173e6afc8928922490d156317503ac4e7bc1c1971a3f7d119863ea5"

      define_method(:install) do
        bin.install "opvar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.0/opvar_0.1.0_darwin_arm64.tar.gz"
      sha256 "770d4fcbcfdbe92f1cf72bda9754acd4f2c9133917ea9aa27c62306de80174ba"

      define_method(:install) do
        bin.install "opvar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.0/opvar_0.1.0_linux_amd64.tar.gz"
      sha256 "f1c2c86a70807cf73386002673f29066834bb0ed12ad7e8479985b8d30ed9b80"
      define_method(:install) do
        bin.install "opvar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrcat71/opvar/releases/download/v0.1.0/opvar_0.1.0_linux_arm64.tar.gz"
      sha256 "31b7f58ced7710ad88e2b72ba22bf0fff34c884f1ac6e2346db0785a752b9309"
      define_method(:install) do
        bin.install "opvar"
      end
    end
  end

  test do
    system "#{bin}/opvar", "--version"
  end
end
